<nav>
    <ul class="sf-menu">
        <li class=""><a href="<?php echo $this->url('home'); ?>">Home</a>
        </li>
        <li><a href="<?php echo $this->url('home',['controller'=>'gallery']); ?>">Gallery</a></li>
        <li><a href="<?php echo $this->url('home',['controller'=>'service']); ?>">Service</a></li>
         <li><a href="<?php echo $this->url('home',['controller'=>'about']); ?>">About</a></li>
         <li><a href="<?php echo $this->url('home',['controller'=>'review']); ?>">Review</a></li>
          <li><a href="<?php echo $this->url('home',['controller'=>'contact']); ?>">Contact</a></li>

    </ul><!-- end menu -->
</nav><!-- end nav -->